### ISSUE TITLE
compile errors

### ISSUE THREAD

**Issue by lucky-wavespider** [romeroperezabel/ARP-RootKit#1]
strreplace undefined
hooks.c:790:15: error: ‘IOPRIO_WHO_PROCESS’ undeclared
hooks.c:790:46: error: ‘IOPRIO_WHO_PGRP’ undeclared

not support kernel version 3.16.x ?
my kernel version is : 3.16.0-67-generic #87~14.04.1-Ubuntu SMP

**Comment by romeroperezabel** [comment]
No, only 4.x
Maybe 3.x in a future.

Sorry.
